run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - gosec
    - prealloc

linters-settings:
  gosec:
    excludes:
      - G104  # unhandled errors on deferred Close()
      - G304  # file path from variable (needed for CLI)

issues:
  exclude-dirs:
    - vendor
    - dist
  max-issues-per-linter: 50
  max-same-issues: 10
