version: 2

project_name: agentveil

builds:
  - id: agentveil-proxy
    main: ./cmd/proxy
    binary: agentveil-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: agentveil-cli
    main: ./cmd/vura
    binary: agentveil
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

dockers:
  - image_templates:
      - "ghcr.io/vurakit/agentveil:{{ .Version }}"
      - "ghcr.io/vurakit/agentveil:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
